### PR TITLE
[WIP] Inline Markdown

### PR DESCRIPTION
**Pull request by Henni**
Just wanted to show you what I'm working.
There is still a lot to do (and clean up).

### CODE REVIEW

**Comment by jancborchardt** [comment]
@Henni is this in a working state yet? Because it somehow doesn’t work for me.

**Comment by Henni** [comment]
@jancborchardt this should work (at least show the editor)

I'll take a look at travis.

**Comment by jancborchardt** [comment]
For me it still shows the 2-up pane, and something at the top as well. No console errors.

**Comment by Henni** [comment]
@jancborchardt please have a look and tell me if it works now.

**Comment by jancborchardt** [comment]
capture du 2015-07-10 13-31-00

Only 2 things from my side:
* [ ] would be awesome if links are clickable. However we could do this in a separate PR
* [ ] I’d actually leave the current typeface, Open Sans. It’s the ownCloud font and a monospace one looks too techy and out of place.

capture du 2015-07-10 13-35-53


Look at this sorcery! @Raydiation @LukasReschke @fcturner @caco3 @DavidPrevot @realrancor

Also cc @jorin-vogel cause this is what we wanted to do for [Litewrite](https://github.com/litewrite). ;)

**Comment by jancborchardt** [comment]
@Henni oh btw, you probably need to rebase your branch.

**Comment by jancborchardt** [comment]
(Also cc @bnvk because we talked about inline markdown plenty of times – there you go! ;)

**Comment by Henni** [comment]
Fixed the font!
Let's fix the links in a different pull request.

Should the `#` be removed in the sidebar?

**Comment by Henni** [comment]
BTW the markdown integration is based on this [markdown-editor](https://github.com/jbt/markdown-editor) by @jbt

**Comment by jancborchardt** [comment]
Yeeha!

> Should the # be removed in the sidebar?

@Henni good question, I also noticed that. I’d say it should be removed and also not be part of the filename, if possible (cause otherwise a bunch of filenames will start with `# ` hash followed by a blank space). What do you think @Raydiation?

**Comment by jancborchardt** [comment]
And huge thanks to @jbt for the great editor! :)

**Comment by jbt** [comment]
Thanks! Great to see it inspiring other stuff :)

FWIW I've spun out the formatted editor component thing into [its own (slightly better organised) project](https://github.com/jbt/mdEdit) - it's still quite experimental but if you come across any bugs or feature requests or general improvements that can be done then do please let me know :)

If you're looking to make links clickable that should be reasonably easy - since it's based on Prism you should be able to use a "wrap" hook [like in the autolinker plugin](https://github.com/PrismJS/prism/blob/gh-pages/plugins/autolinker/prism-autolinker.js#L45) and then apply that to the relevant types.

**Comment by Henni** [comment]
The latest commit hides leading `#` of titles in the sidebar.
The file names still contain leading `#`. To change this some server-side code has to be changed and maybe even the API.
Currently the title generation code is duplicated in the client and the server. Maybe we should extract the title from the content only in the client and send it to the server.
But lets solve this in a separate PR.

**Comment by Raydiation** [comment]
> Currently the title generation code is duplicated in the client and the server. Maybe we should extract the title from the content only in the client and send it to the server.
But lets solve this in a separate PR.

The issue here is that you need to duplicate it to make the change happen instantly. IMHO not an issue.

**Comment by Henni** [comment]
@Raydiation The change would still happen instantly on the client side.
Instead of just passing the content we could also pass the extracted and modified title to the server.
This way the client proposes a title to the server and the server only has to modify it to prevent duplicate files names.

But if you think it's not an issue we can leave it for now.

**Comment by Raydiation** [comment]
Theres also the API ;)

**Comment by Raydiation** [comment]
BTW, beware of XSS for src and href attributes. Clicking on this link should not trigger an alert:

    [click me](javascript:alert(1))

**Comment by Raydiation** [comment]
I personally don't really like how https://github.com/owncloud/notes/pull/118#issuecomment-120391411 looks. I thought inline editing should work more like this:

You type a # sign. the next character you type makes the # sign disappear and turns following text into a h1. If you remove the following text the # sign will reappear. 

The same for making stuff bold with **. e.g.:
** test will not be rendered as bold but as soon as you close it with ** it will remove the ** around it and turn it into bold text. If you try to delete the first or last character of a bold word, it will render back as markdown

The main issue I think that I've got with the approach linked in the screenshot is that it makes notes harder to read. The purpose of markdown is to be rendered so that the "rubbish syntax" disappears and lets you focus on the text instead.

**Comment by Raydiation** [comment]
Check this editor http://textbox.io/

**Comment by Raydiation** [comment]
Works like described and we even got a toolbar to make it easy for people that don't know markdown

**Comment by jancborchardt** [comment]
> The purpose of markdown is to be rendered

No. The purpose of mark_up_ is to be rendered. Markdown was always intended to be readable as is.

Honestly this is what we talked about the whole time and it's working really great. It's easily visible which character causes what. Same as iA Writer for example does.

**Comment by Raydiation** [comment]
I think the editor plugin combines the worst of both worlds:
* No markdown is rendered to normal text so you don't get nice multimedia notes, its some sort of Frankenstein mashup
* The current markdown is rendered in a way that bullet points and other markdown characters are not visible very well, so writing pure markdown is harder than normal

I mean, who do we write this application for? Power users that only use markdown and need visual clues or users that want to take simple notes and just add a link or make something bold? Is this a "learn how to write markdown" tutorial app :D?

In addition solution for making links clickable is just really awkward: the link text is in the brackets and the clickable link is in the normal braces? What kind of sense does that rendering make? Why do I need a link text at all if its not used to replace the link?

What about images? Where should they be rendered?

Why do we need inline editing at all? Because it's fancy or because it should solve usability issues because markdown has a higher learning curve?

**Comment by Raydiation** [comment]
BTW, nothing against the implementation, it's just I don't like how the editor library does things.

**Comment by jancborchardt** [comment]
@Henni @LukasReschke what do you think?

**Comment by Henni** [comment]
@Raydiation I see what you mean, but i think what you describe is a document editor instead of a notes app.
If I write notes I don't want to format them by clicking any buttons. I want to write text and maybe add some emphasis by adding a `#`, `_` or `*` here and there. I think a notes app should be kept simple and be "what you see is what you *really* get". What I mean by this is that a notes app shouldn't alter the content I put in (like removing stars).
I like how this implementation instead supports what I am typing by graying out characters used for emphasis for example.

**Comment by jancborchardt** [comment]
I totally agree with @Henni here. If we want to go WYSIWYG-Editor, then we should be aware of that. And for ppl who want that, maybe [OwnNote](https://github.com/Fmstrat/ownnote/) or the Documents app are a better choice.

**Comment by Raydiation** [comment]
I actually think it should be more like own notes since people seem to like it :)

PS what about images and links?

**Comment by jancborchardt** [comment]
> I actually think it should be more like own notes since people seem to like it :)

Well, then that would be a fundamental change of how the app works. I think we should not do that and just let OwnNotes take care of that.

> PS what about images and links?

As said above, separate pull request. I’d say images should be shown as small preview above the `` code.


So, can we merge this? The Travis failures are probably unrelated? https://github.com/owncloud/notes/issues/121 @LukasReschke @Henni

**Comment by Henni** [comment]
I don't know if we really need images. But if someone wants to implement it: Great!

Links could simply be solved by making the squared brackets area clickable.
```markdown
[this is clickable](https://this.link/is/not/clickable)
```
But let's solve this in a different issue/pull request like @jancborchardt said.

**Comment by Raydiation** [comment]
> Well, then that would be a fundamental change of how the app works. Not using simple text files, supporting formatting etc. I think we should not do that and just let OwnNotes take care of that.

No problem if we simply render the markup inline. 

Which userbase do we actually intend to appeal to? Is the notes app targeted more at developers or average users that mainly consume software?

If you really feel like this is the way to go, we can merge it, I however still have my doubts :)

**Comment by Raydiation** [comment]
PS: @Henni @jancborchardt whoever wants to maintain the comments on the app store can upload it, feel free to do so ;)

**Comment by Raydiation** [comment]
Just pulled onto my production instance :)

Has someone tested editing the News app's Readme? The cursor jumps around very fast (maybe the parser rerenders everything all the time) and editing is basically impossible

**Comment by jancborchardt** [comment]
@Raydiation maybe best open a new issue so discussion can be handled there? :)

**Comment by muramasatheninja** [comment]
Is there a way to disable this? I just updated my notes app with some other updates I was doing and it's driving me up the wall. I typically do my own formatting but it doesn't seem to be able to make up it's mind and I never know what it's going to do to my formatting when I hit enter. Haven't found a place to disable it yet.

**Pull request merged**
