### PR TITLE
Fix directory name in ApiControllerTest

### LINKED ISSUE #121: fix Travis tests
https://travis-ci.org/owncloud/notes/builds

@Raydiation @LukasReschke @Henni @fcturner @caco3 @DavidPrevot @realrancor anyone want to look into this? :)

### PR DESCRIPTION
**Pull request by Henni**
fixes #121 

 @Raydiation I don't understand why the directory name has to be this way. Maybe you can explain it to me...

### CODE REVIEW

**Comment by Raydiation** [comment]
Good catch, my bad :)

**Comment by Henni** [comment]
BTW:
This error message occurs for the files app after I run the notes integration phpunit test.
image

Is this some bug in the integration test, or in the files app or is this intended?

**Comment by Raydiation** [comment]
I've directly pushed a fix https://github.com/owncloud/notes/commit/eadf1e20407e54114409779de7bfd2bc5ce361ff

I've removed the Testcase baseclass since it does all sorts of weird stuff and adds a dummy filesystem layer for performance (which we don't want since we want to test everything all the way down to file creation)

Can you pull and check if it works?

**Comment by Raydiation** [comment]
PS: I've pushed the test at that point even though it was failing because I think it was very important and we needed some sort of base to start integration testing from. Turns out it was a very simple typo that was needed to make it work.

You rock!

**Comment by Henni** [comment]
Thanks. Works now!

**Comment by Raydiation** [comment]
BTW: it would be cool if you could also add a NotesControllerIntegrationTest 

The only thing that probably needs to be replaced is the controller name (NotesApiController to NotesController) and an additional test for the setConfig and getConfig methods

Then we'd pretty much cover the entire app with integration tests which would be awesome as hell.

https://github.com/owncloud/notes/blob/3fd27707380d722af63204f1a07b88ab59e80718/tests/integration/controller/NotesApiControllerTest.php#L38

**Pull request merged**
