### PR TITLE
fix shrinked text area height, fix #77, thanks to @MarvAmBass

### LINKED ISSUE #77: Text area has shrinked height
It seems commits after 09275738b2bcc05fdac0af5715acdef43dcd94a6 breaks the visible text area.
When you edit text and add content, the top is pushed upwards and invisible.

@jancborchardt

### PR DESCRIPTION
**Pull request by jancborchardt**
Please test @fossxplorer @sanneterpstra @beli3ver @LukasReschke @JanMalte @hermanthe

@MarvAmBass thank you for the solution – next time you can just submit a pull request yourself. ;)

### CODE REVIEW

**Comment by JanMalte** [comment]
@jancborchardt This PR fixed the issue for me :+1:

**Comment by jancborchardt** [comment]
@DeepDiver1975 @LukasReschke what’s wrong with the Travis build here? A package.json seems to be expected but missing?

**Comment by LukasReschke** [comment]
Ignore the failing build for now. Will be fixed once I have time to review and adjust  https://github.com/owncloud/notes/pull/82

**Comment by jancborchardt** [comment]
Mergable then? Your call as maintainer @LukasReschke :)

**Comment by LukasReschke** [comment]
Yep. Will do some more changes on the weekend… – For now this is fine. – Busy with 8.0 stuff…

**Comment by MarvAmBass** [comment]
works for me thx

**Pull request merged**
