### PR TITLE
Implement codecov

### PR DESCRIPTION
**Pull request by phil-davis**
@PVince81 please add codecov_token to the drone repo https://drone.owncloud.com/owncloud/notes/settings/secrets
Then we can rerun CI here, and all will be green.

Issue #298

### CODE REVIEW

**Comment by phil-davis** [comment]
Blocked waiting for codecov_token to be added to drone repo.

**Comment by phil-davis** [comment]
@PVince81 ping for codecov_token
I am not sure who else can add the codecov_token - let me know who else I can ping to do it.

**Comment by DeepDiver1975** [comment]
> @PVince81 ping for codecov_token

Just did this @phil-davis

**Comment by DeepDiver1975** [comment]
coverage was uploaded - https://drone.owncloud.com/owncloud/notes/22/46

**Comment by phil-davis** [comment]
I tried putting the integration test coverage report into a different output file `tests/output/clover-integration.xml` but it did not work:
https://drone.owncloud.com/owncloud/notes/26/99 shows that the file exists and seems to have good XML.
https://drone.owncloud.com/owncloud/notes/26/100 shows codecov searching the file but not finding any coverage report???

I changed the code back so it also writes the integration test coverage to `tests/output/clover.xml` and it works.

Do we care? Why doesn't it work when I give the coverage report file a different name?

**Pull request merged**
