### PR TITLE
Migrate to from Grunt to Gulp

### PR DESCRIPTION
**Pull request by Raydiation**
Ground work for #129

@Henni @jancborchardt @LukasReschke

### CODE REVIEW

**Comment by Henni** [comment]
@Raydiation Why do you want to switch to gulp?

**Comment by Raydiation** [comment]
@Henni Angular 2 will be built on Gulp tools mainly and Gulp is **a lot** faster than Grunt because it uses streams instead of file I/O like Grunt. If you look for benchmarks, Gulp is at minimum twice as fast as Grunt (sometimes even 1000 times faster) and the more I/O related tools you've got the bigger the speed distance becomes.

Here are some benchmarks
* http://tech.tmw.co.uk/2014/01/speedtesting-gulp-and-grunt/
* http://elcoding.com/posts/moving-from-grunt-js-to-gulp-js

**Comment by Raydiation** [comment]
Ready to review.

I've also removed unused vendor files btw and fixed the build :)

**Comment by Raydiation** [comment]
And added prism from bower so we can update it easily.

**Comment by Raydiation** [comment]
Merging now because it's probably too big for a review now :/ (got @LukasReschke 's blessing)

We can always revert it, squashed it into to commit and tests and webinterface all work for me locally

**Pull request merged**
