### PR TITLE
Add horizontal line styling

### PR DESCRIPTION
**Pull request by Henni**
depends on #146 

cc @pierrejochem @stefan-niedermann

### CODE REVIEW

**Comment by stefan-niedermann** [comment]
@Henni could you please provide a screenshot?

**Comment by Henni** [comment]
@stefan-niedermann 
image

**Comment by stefan-niedermann** [comment]
nice. some suggestions:
- use a lighter grey for the line
- add some margin-bottom, so there is a bit space between the line and the text below
- :+1:  for text-align: center on the ***

cc @jancborchardt

**Comment by Henni** [comment]
@stefan-niedermann 
like this?
image

**Comment by pierrejochem** [comment]
Leave the stars left in my opinion

**Comment by jancborchardt** [comment]
Great, and I agree with @stefan-niedermann’s suggestions! :)

**Comment by jancborchardt** [comment]
Do the *** invoke the line? If so, they should stay on the left, and be on the same row as the line. That is, the line should start right of the asterisks.

**Comment by Henni** [comment]
@jancborchardt 
image

**Comment by jancborchardt** [comment]
Just slightly less bottom margin (it should be vertically centered between the text above and below) – otherwise it’s great! :+1:

**Comment by stefan-niedermann** [comment]
great!

can minus minus minus also cause a horizontal line? how would it look there (- is lower than *)?

**Comment by Henni** [comment]
@stefan-niedermann 
image
`---` requires an empty line above, else it is interpreted as a heading

**Comment by pierrejochem** [comment]
:+1:

**Comment by jancborchardt** [comment]
:rocket: !

**Pull request merged**
