### PR TITLE
Use proper function

### PR DESCRIPTION
**Pull request by LukasReschke**
index.php may not necessarily be in the URL.

Fixes https://github.com/owncloud/notes/issues/209

### CODE REVIEW

**Comment by BernhardPosselt** [comment]
Just a quick question for understanding this better: whats the difference between generateUrl and link to?

**Comment by LukasReschke** [comment]
> Just a quick question for understanding this better: whats the difference between generateUrl and link to?

It's kinda the same. generateUrl is just the new one that is more flexible (`linkTo` does not work always as it calls `OC.filePath` which is kinda shaddy), could also have taken that one. Would then just be `OC.generateUrl('/apps/notes/')`.

… `linkTo` was just the first thing that came into my mind :see_no_evil:

**Comment by BernhardPosselt** [comment]
:+1:

**Comment by BernhardPosselt** [comment]
The api might still break if you change the URL btw

**Comment by Henni** [comment]
This completely broke the notes app.
I'm preparing a fix for https://github.com/owncloud/notes/issues/205

**Pull request merged**
