### PR TITLE
Add custom favicon

### PR DESCRIPTION
**Pull request by Henni**
Adding a custom icon for the notes app.
favicon
cc @stefan-niedermann

### CODE REVIEW

**Comment by Henni** [comment]
Maybe this actually solves #159 
Could you verify this please @improti

**Comment by improti** [comment]
What exactly do you want me to check?

**Comment by Henni** [comment]
Does this branch fix the issue in firefox?

**Comment by improti** [comment]
Hm, I did a `git pull ` followed by a `git checkout add-favicon`, that was what you wanted, right? If I now go to the notes, then the icon is displayed already on the first time. So yes, it seems to fix the issue.

Thx a lot for your efforts (also in general)! I should switch back to master now, though, shouldn't I?

**Comment by Henni** [comment]
@improti Thanks for testing it! That's exactly what I wanted.
Yes you should switch back to master and pull in a second, after I have merged this PR.

**Pull request merged**
