### PR TITLE
Adjust composer files and app core min-version for 'drop PHP 5.6'

### PR DESCRIPTION
**Pull request by phil-davis**
- [x] adjust local `composer` files to PHP 7.0.8
- [x] bump app core min-version to `10.2`

because the app is now being tested only against core `stable10` upcoming `10.2` that has dropped PHP 5.6 support.

CI on Travis was old and broken, so also implement the CI on drone (issue #298 )
- put "modern" test targets in `Makefile` for phpunit and codestyle tests
- add `.drone.yml` with codestyle, PHP unit and PHP integration testing
- adjust the JS tests to use `phantomJS` browser. (it was using Firefox which would take more effort to sort out on drone)
- put JS test into drone
- cut down Travis so it does "nothing" any more (and so it will pass!_

ToDo after this PR:
- [ ] set the repo to travis not required, drone required
- [ ] delete `.travvis.yml`
- [ ] add codecov_token to the drone repo settings
- [ ] add codecov to suitable PHP test matrix entries
- [ ] add codecov badge the README

### CODE REVIEW

**Comment by phil-davis** [comment]
@PVince81 this repo still runs on Travis and Travis is only testing with PHP 7.1 and 7.2 anyway.

Should we make an issue to move the CI to drone?

**Comment by phil-davis** [comment]
CI on Travis is in trouble. I will look later - no urgency for this tonight!

**Comment by PVince81** [comment]
@phil-davis ok for a ticket, but no priority

**Comment by phil-davis** [comment]
Summary of broken CI on Travis: https://github.com/owncloud/notes/pull/299#issuecomment-472674863
It seems that it will be easier to move straight to drone and not spend time working out how to fix Travis.

**Comment by phil-davis** [comment]
@PVince81 all the previous tests from Travis are running on drone, and the "drop PHP 5.6" changes are here, and CI is green. Please review.

**Comment by phil-davis** [comment]
@PVince81 IMO this is ready.
And it will be easy after this is merged to do the "ToDo after this PR" items and get rid of travis completely in this repo.

**Comment by PVince81** [comment]
@phil-davis please process the remaining todos then, or make a ticket to do so later

**Comment by phil-davis** [comment]
`.travis.yml` removed in PR #300 
@PVince81 please add codecov token to https://drone.owncloud.com/owncloud/notes/settings/secrets - then I can do the next steps.

**Pull request merged**
