### PR TITLE
Add screenshot and fix title

### PR DESCRIPTION
**Pull request by stefan-niedermann**
Title contains now "ownCloud".
https://github.com/owncloud/notes/issues/213
https://github.com/stefan-niedermann/screenshots/commit/a2008c461663a943945475cea0d1cebf731bc482

### CODE REVIEW

**Comment by jancborchardt** [comment]
There is a small strange part of a circle in the bottom left of the screenshot, can you whiten that? :) Otherwise :+1:

**Comment by Henni** [comment]
@stefan-niedermann do you want to take another short look and fix the screenshot?
Additionally I'd like to leave this app cloud neutral (ref https://github.com/owncloud/gallery/pull/696)

**Comment by stefan-niedermann** [comment]
Sure, no problem. but how did you imagine? logo and default theme are still pointing to "one of the two" clouds.......
Or do you mean, just change the title from "ownCloud Notes" to - what - "ownCloud / Nextcloud Notes"?

**Comment by Henni** [comment]
@stefan-niedermann "Notes" should work for now. So let's leave it like it currently is.

This is just about the name. The repository will stay here (owncloud/notes) and we only need one screenshot of the app in one of the clouds.

This means that your screenshot is great, except for:
> There is a small strange part of a circle in the bottom left of the screenshot, can you whiten that? :)

**Comment by stefan-niedermann** [comment]
notes

**Comment by stefan-niedermann** [comment]
notes

**Comment by jancborchardt** [comment]
@stefan-niedermann yup, no need to add the »ownCloud« in the title as it also runs on Nextcloud. As Gallery, Mail and others have made their apps cloud-independent we should do that with Notes too.

@Henni are you at the Meetup this evening? I’ll be in Muc again and @LukasReschke will too :) We can polish the Contacts app more then.

**Comment by stefan-niedermann** [comment]
See https://github.com/owncloud/notes/pull/242 - new pull request, only screenshot :) regards

**Pull request closed without merging**
