### PR TITLE
Fix REST base url

### LINKED ISSUE #205: Can't create new notes from the browser
Hello
I have installed the latest app (2.0.0)

When I click on "New note" nothing happens. I can't write anything in the panel on the right. When I open the firefox console I can see the following message ( I hid my domain)

`POST XHR https://mydomain/index.php/apps/notes/notes [HTTP/2.0 403 Forbidden 245ms]`

I assume it must be something misconfigured somewhere but can't find what it is. 

Also what is strange is that if I create a note from my tablet using the MyOwnNotes app then it gets uploaded to my ownCloud and then I can update these notes from the browser.

### PR DESCRIPTION
**Pull request by Henni**
please review:
@ppmt @Paviluf @gnzsnz @susca @tobiasKaminsky @mikelupe @Lepelaar @DatGizmo
@LukasReschke @BernhardPosselt

### CODE REVIEW

**Comment by DatGizmo** [comment]
@Henni: Works
Notes are shown now. :)

**Comment by Lepelaar** [comment]
Yep! seems to work for me too! :-)

I tested adding/deleting/updating notes, via web, android-app (MyOwnNotes) and desktop (windows)  app (QOwnNotes). All working fine.

Thanx @Henni for the fast action :-)

**Comment by mikelupe** [comment]
Thanks for the speed @Henni - notes appeared :)

**Comment by ppmt** [comment]
I installed version 2.0.1 of Notes and it am still not able to create a new note from the web interface when mod_security is enabled

**Comment by mikelupe** [comment]
@ppmt you have to edit the three files manually in the owncloud/apps directory, I guess there will be a 2.0.2 version in near future that contains those changes.

**Comment by ppmt** [comment]
My files are already like that. I should have said that I installed the branched fix-url rather than just 2.0.1

**Comment by mikelupe** [comment]
@ppmt sorry, I misunderstood, my bad. I additionally restarted apache, just to be sure there was no caching involved... we never know.

**Comment by Henni** [comment]
In conclusion this seems to fix a 404 some users (including me) get.
But it doesn't fix the 403 mentioned by @ppmt and @Paviluf in #205.

**Comment by susca** [comment]
Thank you Henni. Fixed it for me (OC 9.0.1 beta(stable))!

**Comment by lemmy04** [comment]
I am running OC 9.0.2 and still no fix for this.

**Comment by samweisgamdschie** [comment]
hello! what can i do to get this fix? i tried the version from today with git clone but it does not solve the 404 problem for me. I am running 8.1.1 (actually can't upgrade...).

Also do I have to pull another version than master? because owncloud tells me, that notes app (this git pulled version from today) has the version 2.0.0 ...?

**Comment by samweisgamdschie** [comment]
I tried the master version today but without success. After a while debugging I found out that the problem was lying on the assets. I use the option 
  'asset-pipeline.enabled' => true,
in my config.php
So I had to remove /var/www/owncloud/assets directory as it is autogenerated. After this the assets where regenerated and the notes app is working again.

So many thanks for this app again!

**Pull request merged**
