### PR TITLE
heading style details, improve vertical rhythm

### PR DESCRIPTION
**Pull request by jancborchardt**
Just some text styling details, please review @owncloud/designers @Henni @BernhardPosselt @LukasReschke

### CODE REVIEW

**Comment by jancborchardt** [comment]
@tchncs maybe you also want to review this? :)

**Comment by Henni** [comment]
@jancborchardt why did you style h3, h4, ... to look like normal text?

**Comment by jancborchardt** [comment]
@Henni h3 is still bold. But h4–6 are less important and distinguished by the `####` enough. Otherwise h4–6 would fight for attention with the h3.

**Comment by Henni** [comment]
what about bold and italic for h4 (and maybe h5 and h6)?

**Comment by jancborchardt** [comment]
@Henni I’d prefer to not use italic anywhere. It’s not used anywhere else and typographically it looks strange except for serif fonts.

**Comment by Henni** [comment]
:+1:

**Comment by jancborchardt** [comment]
Btw, I used the Notes app the other day for outlining notes and then presenting them, was quite awesome with the markdown and the devs were impressed. ;)

**Pull request merged**
